### ISSUE TITLE
What waning ist this?

### ISSUE THREAD

**Issue by kevin070982** [mining-pool/open-grin-pool#28]
What does that mean?
The Server will stop every night with this code.

goroutine 22 [running]:
main.(*payer).getNewBalance(0xc0000fe0a0, 0x0)
        /home/travis/gopath/src/github.com/maoxs2/open-grin-pool/payer.go:32 +0x39c
main.(*payer).watch.func1(0xc0000fe0a0)
        /home/travis/gopath/src/github.com/maoxs2/open-grin-pool/payer.go:68 +0x3a3
created by main.(*payer).watch
        /home/travis/gopath/src/github.com/maoxs2/open-grin-pool/payer.go:46 +0x3f

**Comment by maoxs2** [comment]
```json
  "wallet": {
    "address": "127.0.0.1",
    "owner_api_port": 3420,
    "auth_user": "epic",
    "auth_pass": "FoakPxzMy56Z4gJPCHKZ"
  },
  "payer": {
    "time": "23:59",
    "fee": 0.01
  }
```
On 23:59, the payer is trying to generate the arrears, but wallet configuration is wrong, so failed to getNewBalance and then panic.

**Comment by kevin070982** [comment]
can you tell me where to set the right values?

**Comment by maoxs2** [comment]
https://github.com/mimblewimble/grin/commit/2ee8d06d483649647e39a172693a7522496b8a27

They had removed this api several days before.

Sorry, I'm taking flu with fever so cannot reply in time.

**Comment by kevin070982** [comment]
OMG. I hope you are well. what state are you in? I am in Zhejiang. Recover well.

**Comment by maoxs2** [comment]
Zhejiang either. 

New API is here https://docs.rs/grin_wallet_api/2.0.0/grin_wallet_api/

**Comment by kevin070982** [comment]
WoW so we are maybe neighbors.
I use your repro for Epic Cash not for grin.

**Comment by kevin070982** [comment]
You are looking for a job right? What program languages do you know fluent?

**Comment by maoxs2** [comment]
try these in bash

```bash
# window 0
epic wallet owner_api

# window 1
curl -X GET http://localhost:3420/v1/wallet/owner/node_height
```

if the response displays the json-wrapped node height, it means that epic wallet is still using v1. And maybe you forgot to maintain the `epic wallet owner_api` command.
