### ISSUE TITLE
index.js

### ISSUE THREAD

**Issue by kevin070982** [mining-pool/open-grin-pool#31]
Currently the blocks are displayed like follow:

- found - f1ds23f1dsf5dsa46d4d6sa4f5df456das4f56ds4f65as4f4d8safd4s8f9ds48fas
- found - r4ew56rew4we8ff45ds6s4afds8f9d4fdsa65fd4sa98f4ds6f4d5s6af4ds56af4
- found - fd4sa56fd4saf4d89sa4fd523ew1r23e1wfda8sf9s4fe5w1fe5wf8a4f9dsafdsf
- found - fds89af41d2s3f1dsa8f9dsa1f5ds6ew1fd9sa3f2d3a1sf8d6f1as23f1ds6a54f1d6s
- found - fe1w6few1f8e9wf1ew562few1f8ew9f4we1f5ew6f1ew8few4fewf5e6wf15ew

can you change the or add the function to send the block hash to

https://explorer.epic.tech/api?q=getblockheight&hash=3933f075332670a661d2271218969770c8396a2853777d5912c9ad4797e9c7e6

an then show the block height?

**Comment by maoxs2** [comment]
"found" block hash is not equals to successfully mined a block, it just means that you have received a correct nonce under current diff, but mining a block requires a the network broadcast and other node's recognization. 

It would be better to run REST API `/v1/blocks/hash` func to get the blocks have successfully mined per specifical time interval. And then export them into a new pool API `/blocks`.
