### ISSUE TITLE
UI not updating GRIN NODE data

### ISSUE THREAD

**Issue by M-Adeel-Danish** [mining-pool/open-grin-pool#33]
Hi @maoxs2, 
First of all thanks a lot for your work and support,

Pool is not throwing any error other than 

> TypeError: pool.mined_blocks is undefinedindex.js:18:21
>     onload http://127.0.0.1/js/index.js:18

 which refers to:

`for (i = 0; i < pool.mined_blocks.length; i++) {`

And I suspect it is blocking the execution of API calls. Which is why no data is being rendered. I have checked API is working fine. Can you explain what I may have done wrong?

**Comment by M-Adeel-Danish** [comment]
Also, miner's stats are not being updated when accessed from the remote browser at `http://ipaddress/miner.html`. This exception is thrown in consol.

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://ipaddress:3330/miner/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

I am using caddy webserver Caddy file.

**Comment by M-Adeel-Danish** [comment]
I have bypassed this loop, grin node data is working. But I couldn't fix this exception. Maybe it has something to do with this issue [CORS](https://github.com/maoxs2/open-grin-pool/issues/34)

**Comment by maoxs2** [comment]
`mined_blocks` is migrated to the new api `http://api_server:api_port/blocks` 

check this commit
https://github.com/maoxs2/open-grin-pool/commit/b91646d8a8f3b64e2618b4e5d527212ef72ac6c2
