### ISSUE TITLE
The Same Origin Policy disallows reading the remote resource

### ISSUE THREAD

**Issue by M-Adeel-Danish** [mining-pool/open-grin-pool#34]
Also, miner's stats are not being updated when accessed from the remote browser at `http://ipaddress/miner.html`. This exception is thrown in consol.

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://ipaddress:3330/miner/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

I am using caddy webserver `Caddyfile`. 

```
:80 {
        root /home/grin/.go/src/open-grin-pool/web
        gzip
        cors
        header / {
                Access-Control-Allow-Origin  "*"
                Access-Control-Allow-Headers "*"
                Access-Control-Allow-Methods "*"
                -Server
        }
}
```
As you can see I have tried to fix the issue by escalating all permissions but without results. How this issue can be resolved?

**Comment by M-Adeel-Danish** [comment]
I was directly accessing localhost/miner.html which didn't have permissions on Go-server, hence the error. 2ndly it was meant to access from the search bar at the landing page with `Miner login ID`. Which fixes the problem. However, some times It is redirecting to MainPage,  is it a bug?

**Comment by maoxs2** [comment]
Have you edit the config.js in web directory and replace the placeholder with your api address?

There shouldn't have any CORS error. Because the pool has `header.Set("Access-Control-Allow-Origin", "*")`, the requests from all sources are allowed.
