### ISSUE TITLE
go build .  on Ubuntu 18.04

### ISSUE THREAD

**Issue by noipstream** [mining-pool/open-grin-pool#37]
# _/root/grin/open-grin-pool
./db.go:27:15: error: not enough arguments
  _, err := rdb.Ping().Result()
               ^
./db.go:36:33: error: argument 1 has incompatible type (type has no methods)
  _, err := db.client.HMSet("user:"+login, map[string]interface{}{
                                 ^
./db.go:36:43: error: argument 2 has incompatible type
  _, err := db.client.HMSet("user:"+login, map[string]interface{}{
                                           ^
./db.go:55:39: error: argument 1 has incompatible type (type has no methods)
  passInDB, err := db.client.HGet("user:"+login, "pass").Result()
                                       ^
./db.go:55:28: error: not enough arguments
  passInDB, err := db.client.HGet("user:"+login, "pass").Result()
                            ^
./db.go:72:33: error: argument 1 has incompatible type (type has no methods)
  _, err := db.client.HMSet("user:"+login, map[string]interface{}{
                                 ^
./db.go:72:43: error: argument 2 has incompatible type
  _, err := db.client.HMSet("user:"+login, map[string]interface{}{
                                           ^
./db.go:84:32: error: argument 1 has incompatible type (type has no methods)
  _, err := db.client.HSet("user:"+login, "lastShare", time.Now().UnixNano()).Result()
                                ^
./db.go:91:36: error: argument 1 has incompatible type (type has no methods)
  _, err := db.client.HIncrBy("shares", login, diff).Result()
                                    ^
./db.go:91:47: error: argument 3 has incompatible type (cannot use type int64 as type string)
  _, err := db.client.HIncrBy("shares", login, diff).Result()
                                               ^
./db.go:91:21: error: not enough arguments
  _, err := db.client.HIncrBy("shares", login, diff).Result()
                     ^
./db.go:102:31: error: argument 1 has incompatible type (type has no methods)
  _, err := db.client.ZAdd("tmp:"+login+":"+agent, z).Result()
                               ^
./db.go:102:51: error: argument 2 has incompatible type (cannot use type redis.Z as type string)
  _, err := db.client.ZAdd("tmp:"+login+":"+agent, z).Result()
                                                   ^
./db.go:109:41: error: argument 1 has incompatible type (type has no methods)
  shares, err := db.client.HGetAll("shares").Result()
                                         ^
./db.go:109:26: error: not enough arguments
  shares, err := db.client.HGetAll("shares").Result()
                          ^
./db.go:118:35: error: argument 1 has incompatible type (type has no methods)
  m, err := db.client.HGetAll("user:" + login).Result()
                                   ^
./db.go:118:21: error: not enough arguments
  m, err := db.client.HGetAll("user:" + login).Result()
                     ^
./db.go:138:55: error: argument 1 has incompatible type (type has no methods)
  dayRevenues, _ := db.client.ZRangeWithScores("revenue:"+login, int64(dateStart), int64(dateEnd)).Result()
                                                       ^
./db.go:138:65: error: argument 2 has incompatible type (cannot use type int64 as type string)
  dayRevenues, _ := db.client.ZRangeWithScores("revenue:"+login, int64(dateStart), int64(dateEnd)).Result()
                                                                 ^
./db.go:138:29: error: not enough arguments
  dayRevenues, _ := db.client.ZRangeWithScores("revenue:"+login, int64(dateStart), int64(dateEnd)).Result()
                             ^
./db.go:157:32: error: argument 1 has incompatible type (type has no methods)
  s, err := db.client.HGet("user:"+login, "agents").Result()
                                ^
./db.go:157:21: error: not enough arguments
  s, err := db.client.HGet("user:"+login, "agents").Result()
                     ^
./db.go:162:40: error: argument 1 has incompatible type (type has no methods)
  strUnixNano, _ := db.client.HGet("user:"+login, "lastShare").Result()
                                        ^
./db.go:162:29: error: not enough arguments
  strUnixNano, _ := db.client.HGet("user:"+login, "lastShare").Result()
                             ^
./db.go:174:43: error: argument 1 has incompatible type (type has no methods)
  l, err := db.client.ZRangeWithScores("tmp:"+login+":"+agent, 0, -1).Result()
                                           ^
./db.go:174:63: error: argument 2 has incompatible type (cannot use type int as type string)
  l, err := db.client.ZRangeWithScores("tmp:"+login+":"+agent, 0, -1).Result()
                                                               ^
./db.go:174:21: error: not enough arguments
  l, err := db.client.ZRangeWithScores("tmp:"+login+":"+agent, 0, -1).Result()
                     ^
./db.go:173:33: error: argument 1 has incompatible type (type has no methods)
  db.client.ZRemRangeByScore("tmp:"+login+":"+agent, "-inf", fmt.Sprint("(", time.Now().UnixNano()-10*time.Minute.Nanoseconds()))
                                 ^
./db.go:173:11: error: not enough arguments
  db.client.ZRemRangeByScore("tmp:"+login+":"+agent, "-inf", fmt.Sprint("(", time.Now().UnixNano()-10*time.Minute.Nanoseconds()))
           ^
./db.go:198:31: error: argument 1 has incompatible type (type has no methods)
  _, err = db.client.HSet("user:"+login, "agents", raw).Result()
                               ^
./db.go:205:39: error: argument 1 has incompatible type (type has no methods)
  _, err := db.client.LPush("blocksFound", hash).Result()
                                       ^
./db.go:212:40: error: argument 1 has incompatible type (type has no methods)
  l, err := db.client.LRange("blocksFound", pos, -1).Result()
                                        ^
./db.go:212:44: error: argument 2 has incompatible type (cannot use type int64 as type string)
  l, err := db.client.LRange("blocksFound", pos, -1).Result()
                                            ^
./db.go:212:21: error: not enough arguments
  l, err := db.client.LRange("blocksFound", pos, -1).Result()
                     ^
./db.go:231:39: error: argument 1 has incompatible type (type has no methods)
  _, err := db.client.LPush("blocksMined", raw).Result()
                                       ^
./db.go:231:43: error: argument 2 has incompatible type
  _, err := db.client.LPush("blocksMined", raw).Result()
                                           ^
./db.go:240:40: error: argument 1 has incompatible type (type has no methods)
  l, err := db.client.LRange("blocksMined", 0, -1).Result()
                                        ^
./db.go:240:44: error: argument 2 has incompatible type (cannot use type int as type string)
  l, err := db.client.LRange("blocksMined", 0, -1).Result()
                                            ^
./db.go:240:21: error: not enough arguments
  l, err := db.client.LRange("blocksMined", 0, -1).Result()
                     ^
./db.go:255:58: error: argument 1 has incompatible type (type has no methods)
  allMinersStrSharesTable, err := db.client.HGetAll("shares").Result()
                                                          ^
./db.go:255:43: error: not enough arguments
  allMinersStrSharesTable, err := db.client.HGetAll("shares").Result()
                                           ^
./db.go:277:31: error: argument 1 has incompatible type (type has no methods)
  _, err = db.client.HDel("share").Result()
                               ^
./db.go:277:20: error: argument 2 has incompatible type
  _, err = db.client.HDel("share").Result()
                    ^
./db.go:277:20: error: not enough arguments
./db.go:288:37: error: argument 1 has incompatible type (type has no methods)
   payment, _ := db.client.HGet("user:"+miner, "payment").Result()
                                     ^
./db.go:288:26: error: not enough arguments
   payment, _ := db.client.HGet("user:"+miner, "payment").Result()
                          ^
./db.go:296:36: error: argument 1 has incompatible type (type has no methods)
   _, err := db.client.ZAdd("revenue:"+miner, z).Result()
                                    ^
./db.go:296:46: error: argument 2 has incompatible type (cannot use type redis.Z as type string)
   _, err := db.client.ZAdd("revenue:"+miner, z).Result()
                                              ^
./db.go:302:32: error: argument 1 has incompatible type (type has no methods)
  db.client.HMSet("lastDayRevenue", allMinersRevenueTable)
                                ^
./db.go:302:36: error: argument 2 has incompatible type
  db.client.HMSet("lastDayRevenue", allMinersRevenueTable)
                                    ^
./db.go:308:64: error: argument 1 has incompatible type (type has no methods)
  allMinersRevenueTable, err := db.client.HGetAll("lastDayRevenue").Result()
                                                                ^
./db.go:308:41: error: not enough arguments
  allMinersRevenueTable, err := db.client.HGetAll("lastDayRevenue").Result()

**Comment by C0MM4ND** [comment]
Make sure you are using go.mod first on your local machine.

If you feel hard to solve, [release binaries](https://github.com/mining-pool/open-grin-pool/releases) are reliable alternatives.

**Comment by noipstream** [comment]
I can`t get nginx to run .js files. 



Any specific setup for nginx ?





---- On Sun, 21 Jun 2020 16:42:13 +0300 Command <notifications@github.com> wrote ----




Make sure you are using go.mod first on your local machine.

If you feel hard to solve, https://github.com/mining-pool/open-grin-pool/releases are reliable alternatives.

**Comment by C0MM4ND** [comment]
Use the default config of nginx is enough. Just putting the files into the folder which nginx is serving(default one is named `html`).

**Comment by noipstream** [comment]
I setup stratum user and pass in miner config but is cant login to miner page.
Nothing is happening when i press GO. 
It remain at home page.
![Screen Shot 2020-06-23 at 11 19 16 AM](https://user-images.githubusercontent.com/56949534/85378807-b1e17300-b543-11ea-91e7-cbbacf9e6b8d.png)

**Comment by C0MM4ND** [comment]
@noipstream Any error on browser's console? Please provide it to help me locate the problem.

**Comment by noipstream** [comment]
Hi ,



I did not get any errors at all. I instaled on two different servers and had same issue. In ssl mode is not displaying anything at all from api.

Do you know any working website?




---- On Thu, 25 Jun 2020 18:08:38 +0300 Command <notifications@github.com> wrote ----





https://github.com/noipstream Any error on browser's console? Please provide it to help me locate the problem.

**Comment by C0MM4ND** [comment]
Button's problem has been fixed, the reason of which is the conflict between default UI event from new UI design #27  and our event.

The private pool which I officially supported had been closed due to epic's price dump. But you shall be able to find others' pool in other issues.
