### ISSUE TITLE
EPIC miner compatibility

### ISSUE THREAD

**Issue by coughLozenge** [mining-pool/open-grin-pool#40]
I know of three miners that can mine EPIC. The reference miner, TT-Miner and SRBMiner.
The only one I can't get to run properly with open-grin-pool is SRBMiner. It reconnects with error:
PARSE error: Received method is not supported
I know other pool software handles this miner so maybe something can be done here. Thanks.

![error-1 - Copy](https://user-images.githubusercontent.com/106449031/200135161-13789fad-c003-4088-8916-aaf43912cf57.png)

![error-2 - Copy](https://user-images.githubusercontent.com/106449031/200135201-345cd668-90b7-40a7-89d7-6b6368a35c75.png)

**Comment by C0MM4ND** [comment]
Plz capture the tcp stream (dont tls encrypt) with wireshark or tcpdump, and upload it to this issue. Or I dont know which method causing the error.

**Comment by coughLozenge** [comment]
Hello @C0MM4ND, thanks for the response. I believe the issue is with method "status".
[srbWireshark.zip](https://github.com/mining-pool/open-grin-pool/files/9958829/srbWireshark.zip)
